### ISSUE TITLE
Multi-download failed due to missing files

### ISSUE THREAD

**Issue by PaulPrice** [conda/infrastructure#949]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In the process of attempting a `mamba install` of several packages, I got:

```
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/pandoc-3.2-ha770c72_0.conda] 567 bytes
```

Working around that by installing an earlier version of `pandoc`, I then get:

```
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/mpi-1.0-mpich.tar.bz2] 561 bytes
```

There seem to be multiple files that don't exist on the server.

### Conda Info

```shell
pprice@tiger2-sumire:/scratch/gpfs/pprice/20240528 $ ./conda/miniconda3-py38_4.9.2/bin/conda info

     active environment : None
       user config file : /home/pprice/.condarc
 populated config files : /home/pprice/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.8.19.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=24.5.0=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2  (writable)
      conda av data dir : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/pkgs
                          /home/pprice/.conda/pkgs
       envs directories : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/envs
                          /home/pprice/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.8.19 Linux/3.10.0-1160.118.1.el7.x86_64 rhel/7.9 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 90096:30000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
pprice@tiger2-sumire:/scratch/gpfs/pprice/20240528 $ ./conda/miniconda3-py38_4.9.2/bin/conda config --show-sources
==> /home/pprice/.condarc <==
channels:
  - conda-forge
```

### Conda list

```shell
base environment : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.pprice@tiger2-sumire:/scratch/gpfs/pprice/20240528 $ ./conda/miniconda3-py38_4.9.2/bin/conda list --show-channel-urls
# packages in environment at /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0            py38h17151c0_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py38h6d47a40_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     24.5.0           py38h578d9bd_0    conda-forge
conda-libmamba-solver     24.1.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cryptography              42.0.7           py38h1407eca_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
fmt                       10.2.1               h00ab1b0_0    conda-forge
frozendict                2.4.4            py38hfb59056_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4              py38h578d9bd_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_1    conda-forge
libarchive                3.7.2                h2aa1ff5_1    conda-forge
libcurl                   8.7.1                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libmamba                  1.5.8                had39da4_0    conda-forge
libmambapy                1.5.8            py38h5cd715c_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsolv                   0.7.29               ha6fb4c9_0    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               hc051c1a_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mamba                     1.5.8            py38haad2881_0    conda-forge
menuinst                  2.0.2            py38h578d9bd_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
openssl                   3.3.0                h4ab18f5_3    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6            py38h01eb140_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyopenssl                 24.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.19          hd12c33a_0_cpython    conda-forge
python_abi                3.8                      4_cp38    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.40          py38h01eb140_0    conda-forge
ruamel.yaml.clib          0.2.8            py38h01eb140_0    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zstandard                 0.22.0           py38ha98ab4e_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by beckermr** [comment]
We've seen multiple failed downloads of artifacts from the CDN.

**Comment by jakirkham** [comment]
cc @jezdez

**Comment by dholth** [comment]
How do we wind up with this URL `https://conda.anaconda.org/conda-forge/mpi-1.0-mpich.tar.bz2` without a subdir like `https://conda.anaconda.org/conda-forge/linux-64/mpi-1.0-mpich.tar.bz2`?

**Comment by PaulPrice** [comment]
Possibly related: there are also a bunch of warnings, e.g.:
```
warning  libmamba Extracted package cache '/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/pkgs/_libgcc_mutex-0.1-conda_forge' has invalid url        
warning  libmamba Extracted package cache '/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/pkgs/libstdcxx-ng-13.2.0-hc0a3c3a_7' has invalid url       
```

**Comment by jakirkham** [comment]
Paul, could you please share the command run that leads to these issues?

Am not seeing it above, but please let me know if I just missed it somewhere

**Comment by PaulPrice** [comment]
It's part of a big script, and I've been playing around a bit to try to get things to work, but I've attempted to distill the bits of interest below, and I've also appended a more complete error message. Please keep in mind that I'm not very familiar with `conda` (so I could be doing something stupid) and I'm deliberately using an older release (which is not ideal, but reasons). I'm happy to provide more outputs, if you desire. Thank you!

After installing miniconda:
```
echo "conda==22.11.1" >> conda/current/conda-meta/pinned
echo "requests=2.31.0" >> conda/current/conda-meta/pinned  # Maybe not necessary
echo "setuptools=69.5.1" >> conda/current/conda-meta/pinned  # Maybe not necessary
conda update -n base -c conda-forge -y conda
conda install -c conda-forge -y mamba=1.5.8 requests=2.31.0 setuptools=69.5.1 menuinst=2.0.2 conda-package-handling=2.2.0
mamba create -y --name lsst-scipipe-3.0.0 --strict-channel-priority -c conda-forge rubin-env=3.0.0 mkl jupyter notebook<7 ipython ipympl ipywidgets jupyter_contrib_nbextensions astroplan ipyevents ginga mypy black isort pygithub pyopenssl=22.0.0 cryptography=37.0.4 cffi=1.15.1 matplotlib=3.6 pydantic=1.10.10 astrowidgets pybind11=2.10.4 zstd=1.5.2 pandoc=2.19.2  # This fails with segfault
```

Output:
```
Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/git-lfs-3.5.1-ha770c72_0.conda] 570 bytes
0�'�U�U1ab_0.conda extraction failed
error    libmamba Error when extracting package: std::bad_alloc

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/mamba/mamba.py", line 959, in exception_converter
        raise e
      File "/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/mamba/mamba.py", line 952, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/mamba/mamba.py", line 898, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/mamba/mamba.py", line 767, in do_call
        exit_code = create(args, parser)
      File "/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/mamba/mamba.py", line 602, in create
        return install(args, parser, "create")
      File "/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/mamba/mamba.py", line 558, in install
        transaction.fetch_extract_packages()
    RuntimeError: Multi-download failed. Reason: Transfer finalized, status: 404 [https://conda.anaconda.org/conda-forge/git-lfs-3.5.1-ha770c72_0.conda] 570 bytes

`$ /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/mamba create -y --name lsst-scipipe-3.0.0 --strict-channel-priority -c conda-forge rubin-env=3.0.0 mkl jupyter notebook<7 ipython ipympl ipywidgets jupyter_contrib_nbextensions astroplan ipyevents ginga mypy black isort pygithub pyopenssl=22.0.0 cryptography=37.0.4 cffi=1.15.1 matplotlib=3.6 pydantic=1.10.10 astrowidgets pybind11=2.10.4 zstd=1.5.2 pandoc=2.19.2`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/conda
             CONDA_PREFIX=/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python
               CONDA_ROOT=/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2
              CONDA_SHLVL=1
                    CPATH=/home/pprice/local/Linux.x86_64/include:/home/pprice/local/Linux.x86_6
                          4/include
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/home/pprice/local/Linux.x86_64/lib:/opt/rh/httpd24/root/usr/lib64
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/home/pprice/local/Linux.x86_64/lib:/home/pprice/local/Linux.x86_64/li
                          b
                  MANPATH=/home/pprice/local/Linux.x86_64/man:/usr/local/share/man:/opt/rh/rh-gi
                          t218/root/usr/share/man:/usr/share/man:/usr/local/share/man:/opt/puppe
                          tlabs/puppet/share/man:
               MODULEPATH=/home/pprice/Modules/modulefiles:/home/pprice/Modules/modulefiles:/usr
                          /share/Modules/modulefiles:/etc/modulefiles:/usr/local/share/Modules/m
                          odulefiles:/opt/share/Modules/modulefiles:/usr/licensed/Modules/module
                          files:/projects/SOFTWARE/Modules/modulefiles/tiger
                     PATH=/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin:/scratch
                          /gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin:/scratch/gpfs/pp
                          rice/20240528/conda/miniconda3-py38_4.9.2/bin:/scratch/gpfs/pprice/202
                          40528/conda/miniconda3-py38_4.9.2/condabin:/home/pprice/local/Linux.x8
                          6_64/bin:/home/pprice/bin:/usr/local/bin:/home/pprice/local/Linux.x86_
                          64/bin:/home/pprice/bin:/usr/local/bin:/opt/rh/rh-git218/root/usr/bin:
                          /usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbi
                          n:/opt/puppetlabs/bin:/opt/dell/srvadmin/bin:/home/pprice/.local/bin:/
                          home/pprice/bin:/home/pprice/.local/bin:/home/pprice/bin
          PKG_CONFIG_PATH=/home/pprice/local/Linux.x86_64/lib/pkgconfig:/home/pprice/local/Linux
                          .x86_64/lib/pkgconfig
               PYTHONPATH=/home/pprice/local/Linux.x86_64/lib/python:/home/pprice/Python:/home/p
                          price/local/Linux.x86_64/lib/python:/home/pprice/Python
            PYTHONSTARTUP=/home/pprice/Python/pythonstartup.py
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2
            shell level : 1
       user config file : /home/pprice/.condarc
 populated config files : /home/pprice/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.8.19.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=24.5.0=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2  (writable)
      conda av data dir : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/pkgs
                          /home/pprice/.conda/pkgs
       envs directories : /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/envs
                          /home/pprice/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.8.19 Linux/3.10.0-1160.118.1.el7.x86_64 rhel/7.9 glibc/2.17 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 90096:30000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

��U3-noxft_h4845f30_101.con� extraction failed
error    libmamba Error when extracting package: [json.exception.type_error.316] invalid UTF-8 byte at index 5: 0x55
*** Error in `/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python': corrupted double-linked list: 0x000055bdebef9130 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x8097f)[0x2b1502c4f97f]
/lib64/libc.so.6(+0x8120e)[0x2b1502c5020e]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/libmambapy/bindings.cpython-38-x86_64-linux-gnu.so(+0x51fb9)[0x2b150af1cfb9]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/libmambapy/bindings.cpython-38-x86_64-linux-gnu.so(+0x331d9)[0x2b150aefe1d9]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x11fde7)[0x55bde7ebade7]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1304f6)[0x55bde7ecb4f6]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1304ec)[0x55bde7ecb4ec]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1304ec)[0x55bde7ecb4ec]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1304ec)[0x55bde7ecb4ec]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1304ec)[0x55bde7ecb4ec]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1304ec)[0x55bde7ecb4ec]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x20c87a)[0x55bde7fa787a]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x10cf8c)[0x55bde7ea7f8c]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1ab75d)[0x55bde7f4675d]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(PyGC_Collect+0x55)[0x55bde7f6dbf5]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(Py_FinalizeEx+0x71)[0x55bde7f6d241]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(Py_Exit+0x8)[0x55bde7e2bff6]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x90f59)[0x55bde7e2bf59]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x90bfc)[0x55bde7e2bbfc]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(PyRun_SimpleFileExFlags+0x3d5)[0x55bde7e34a78]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x8d3fa)[0x55bde7e283fa]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(Py_BytesMain+0x37)[0x55bde7f3ef37]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b1502bf1555]
/scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/bin/python(+0x1a3e3d)[0x55bde7f3ee3d]
======= Memory map: ========
2b1502086000-2b15020a8000 r-xp 00000000 fd:00 100687606                  /usr/lib64/ld-2.17.so
2b15020a8000-2b15020a9000 rw-p 00000000 00:00 0 
2b15020a9000-2b15020b0000 r--s 00000000 fd:00 78928214                   /usr/lib64/gconv/gconv-modules.cache
2b15020b0000-2b15020b1000 r--p 00000000 00:30 317348611                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
2b15020b1000-2b15020b4000 r-xp 00001000 00:30 317348611                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
2b15020b4000-2b15020b7000 r--p 00004000 00:30 317348611                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
2b15020b7000-2b15020b8000 r--p 00006000 00:30 317348611                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
2b15020b8000-2b15020b9000 rw-p 00007000 00:30 317348611                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so
2b15020b9000-2b15020bc000 r--p 00000000 00:30 312222909                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so
2b15020bc000-2b15020c2000 r-xp 00003000 00:30 312222909                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so
2b15020c2000-2b15020c4000 r--p 00009000 00:30 312222909                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so
2b15020c4000-2b15020c5000 r--p 0000a000 00:30 312222909                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so
2b15020c5000-2b15020c6000 rw-p 0000b000 00:30 312222909                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so
2b15020c6000-2b15020ca000 r--p 00000000 00:30 479322660                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/frozendict/_frozendict.cpython-38-x86_64-linux-gnu.so
2b15020ca000-2b15020d0000 r-xp 00004000 00:30 479322660                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/frozendict/_frozendict.cpython-38-x86_64-linux-gnu.so
2b15020d0000-2b15020d3000 r--p 0000a000 00:30 479322660                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/frozendict/_frozendict.cpython-38-x86_64-linux-gnu.so
2b15020d3000-2b15020d4000 r--p 0000c000 00:30 479322660                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/frozendict/_frozendict.cpython-38-x86_64-linux-gnu.so
2b15020d4000-2b15020d6000 rw-p 0000d000 00:30 479322660                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/site-packages/frozendict/_frozendict.cpython-38-x86_64-linux-gnu.so
2b15020d6000-2b15020d8000 rw-p 00000000 00:00 0 
2b15020da000-2b150229f000 rw-p 00000000 00:00 0 
2b150229f000-2b15022a1000 r--p 00000000 00:30 318373852                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
2b15022a1000-2b15022a3000 r-xp 00002000 00:30 318373852                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
2b15022a3000-2b15022a5000 r--p 00004000 00:30 318373852                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
2b15022a5000-2b15022a6000 r--p 00005000 00:30 318373852                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
2b15022a6000-2b15022a7000 rw-p 00006000 00:30 318373852                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so
2b15022a7000-2b15022a8000 r--p 00021000 fd:00 100687606                  /usr/lib64/ld-2.17.so
2b15022a8000-2b15022a9000 rw-p 00022000 fd:00 100687606                  /usr/lib64/ld-2.17.so
2b15022a9000-2b15022aa000 rw-p 00000000 00:00 0 
2b15022aa000-2b15022c1000 r-xp 00000000 fd:00 100949280                  /usr/lib64/libpthread-2.17.so
2b15022c1000-2b15024c0000 ---p 00017000 fd:00 100949280                  /usr/lib64/libpthread-2.17.so
2b15024c0000-2b15024c1000 r--p 00016000 fd:00 100949280                  /usr/lib64/libpthread-2.17.so
2b15024c1000-2b15024c2000 rw-p 00017000 fd:00 100949280                  /usr/lib64/libpthread-2.17.so
2b15024c2000-2b15024c6000 rw-p 00000000 00:00 0 
2b15024c6000-2b15024c8000 r-xp 00000000 fd:00 100932063                  /usr/lib64/libdl-2.17.so
2b15024c8000-2b15026c8000 ---p 00002000 fd:00 100932063                  /usr/lib64/libdl-2.17.so
2b15026c8000-2b15026c9000 r--p 00002000 fd:00 100932063                  /usr/lib64/libdl-2.17.so
2b15026c9000-2b15026ca000 rw-p 00003000 fd:00 100932063                  /usr/lib64/libdl-2.17.so
2b15026ca000-2b15026cc000 r-xp 00000000 fd:00 100949292                  /usr/lib64/libutil-2.17.so
2b15026cc000-2b15028cb000 ---p 00002000 fd:00 100949292                  /usr/lib64/libutil-2.17.so
2b15028cb000-2b15028cc000 r--p 00001000 fd:00 100949292                  /usr/lib64/libutil-2.17.so
2b15028cc000-2b15028cd000 rw-p 00002000 fd:00 100949292                  /usr/lib64/libutil-2.17.so
2b15028cd000-2b15029ce000 r-xp 00000000 fd:00 100948825                  /usr/lib64/libm-2.17.so
2b15029ce000-2b1502bcd000 ---p 00101000 fd:00 100948825                  /usr/lib64/libm-2.17.so
2b1502bcd000-2b1502bce000 r--p 00100000 fd:00 100948825                  /usr/lib64/libm-2.17.so
2b1502bce000-2b1502bcf000 rw-p 00101000 fd:00 100948825                  /usr/lib64/libm-2.17.so
2b1502bcf000-2b1502d93000 r-xp 00000000 fd:00 100800137                  /usr/lib64/libc-2.17.so
2b1502d93000-2b1502f92000 ---p 001c4000 fd:00 100800137                  /usr/lib64/libc-2.17.so
2b1502f92000-2b1502f96000 r--p 001c3000 fd:00 100800137                  /usr/lib64/libc-2.17.so
2b1502f96000-2b1502f98000 rw-p 001c7000 fd:00 100800137                  /usr/lib64/libc-2.17.so
2b1502f98000-2b1502f9d000 rw-p 00000000 00:00 0 
2b1502f9d000-2b1502fa4000 r-xp 00000000 fd:00 100949286                  /usr/lib64/librt-2.17.so
2b1502fa4000-2b15031a3000 ---p 00007000 fd:00 100949286                  /usr/lib64/librt-2.17.so
2b15031a3000-2b15031a4000 r--p 00006000 fd:00 100949286                  /usr/lib64/librt-2.17.so
2b15031a4000-2b15031a5000 rw-p 00007000 fd:00 100949286                  /usr/lib64/librt-2.17.so
2b15031a5000-2b15096e8000 r--p 00000000 fd:00 67253019                   /usr/lib/locale/locale-archive
2b15096e8000-2b1509868000 rw-p 00000000 00:00 0 
2b1509868000-2b150986c000 r--p 00000000 00:30 308122248                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/array.cpython-38-x86_64-linux-gnu.so
2b150986c000-2b1509872000 r-xp 00004000 00:30 308122248                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/array.cpython-38-x86_64-linux-gnu.so
2b1509872000-2b1509876000 r--p 0000a000 00:30 308122248                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/array.cpython-38-x86_64-linux-gnu.so
2b1509876000-2b1509877000 r--p 0000e000 00:30 308122248                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/array.cpython-38-x86_64-linux-gnu.so
2b1509877000-2b1509878000 rw-p 0000f000 00:30 308122248                  /scratch/gpfs/pprice/20240528/conda/miniconda3-py38_4.9.2/lib/python3.8/lib-dynload/array.cpython-38-x86_64-linux-gnu.sonewinstall.sh: line 501: 56721 Aborted                 $cmd mamba "${args[@]}"
```

**Comment by PaulPrice** [comment]
Our build test worked over the weekend, so I guess this magically resolved?
